#####
# This file is duplicated to individual samples from the global scripts/libs.versions.toml
# Do not add a dependency to an individual sample, edit the global version instead.
#####
[versions]
accompanist = "0.36.0"
androidGradlePlugin = "8.12.3"
androidx-activity-compose = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-compose-bom = "2025.09.01"
androidx-constraintlayout = "1.1.1"
androidx-corektx = "1.17.0"
androidx-lifecycle-compose = "2.9.4"
androidx-lifecycle-runtime = "2.9.4"
androidx-lifecycle-runtime-compose = "2.9.4"
androidx-navigation = "2.9.5"
androidx-palette = "1.0.0"
androidx-datastore-preferences = "1.1.7"
androidx-test = "1.7.0"
androidx-test-espresso = "3.5.1"
androidx-test-ext-junit = "1.3.0"
androidx-test-ext-truth = "1.7.0"
androidx-arch-core-testing = "2.2.0"
androidx-window = "1.2.0"
coil = "2.2.0"
google-firebase-bom = "33.4.0"
google-firebase-crashlytics = "19.2.0"
google-firebase-analytics = "22.1.2"
google-firebase-analytics-ktx = "21.5.1"
googleServicesPlugin = "4.4.3"
crashlyticsPlugin = "3.0.6"
# @keep
compileSdk = "36"
compose-compiler = "1.5.10"
coroutines = "1.10.2"
gradle-versions = "0.46.0"
# @pin When updating to AGP 7.4.0-alpha10 and up we can update this https://developer.android.com/studio/write/java8-support#library-desugaring-versions
jdkDesugar = "2.0.4"
junit = "4.13.2"
# @pin Update in conjuction with Compose Compiler
kotlin = "2.2.20"
ksp = "1.9.20-1.0.14"
maps-compose = "2.5.3"
pluginCompose = "2.2.20"
material = "1.13.0"
# @keep
minSdk = "21"
okhttp = "4.10.0"
# @keep
targetSdk = "36"
version-catalog-update = "0.8.0"
espressoCore = "3.7.0"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-materialWindow = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-googlefonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-corektx" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime-compose" }
androidx-lifecycle-viewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-preferences" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-ext-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-ext-truth" }
androidx-test-runner = "androidx.test:runner:1.5.2"
google-android-material = { module = "com.google.android.material:material", version.ref = "material" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "google-firebase-bom" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "google-firebase-crashlytics" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "google-firebase-analytics" }

junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "pluginCompose" }

